# Generated by Django 5.1.7 on 2025-05-26 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
